In [1]:
import numpy as np
import sys
import pyDOE as pyDOE
import corner
from sympy import symbols, Eq

In [2]:
# Parameters
n_params = 7
n_samples = 1400

# parameter ranges:
h = np.linspace(0.62, 0.78, n_samples)
ombh2 = np.linspace(0.0180, 0.0250, n_samples)
omch2 = np.linspace(0.050, 0.250, n_samples)
ns = np.linspace(0.88, 1.06, n_samples)
z = np.linspace(0.0, 8.0, n_samples)
lnAs = np.linspace(2.60, 3.90, n_samples)                  # ln(10^{10}As)
w = np.linspace(-1.5, -0.6, n_samples)                   # eqn of state parameter
#omnuh2 = np.linspace(, n_samples)
#N_eff =  np.linspace(1.00, 3.00,  n_samples)

%%time
for i in range(2000):
    m = np.exp(2.99+i/100)/(10**10)
    i +=1
    print(m)

In [4]:
# LHS Grid
AllParams = np.vstack([h, ombh2, omch2, ns, z, lnAs, w])
lhd = pyDOE.lhs(n_params, samples=n_samples, criterion=None)
index = (lhd*n_samples).astype(int)

AllCombs = np.zeros((n_samples, n_params))
for i in range(n_params):
    AllCombs[:, i] = AllParams[i][index[:, i]]
    
print(np.shape(AllCombs))
print(np.shape(AllParams))
print(type(AllParams))

(1400, 7)
(7, 1400)
<class 'numpy.ndarray'>


In [5]:
params = {'h': AllCombs[:, 0],
          'omega_b': AllCombs[:, 1],
          'omega_cdm': AllCombs[:, 2],
          'ns': AllCombs[:, 3],
          'z': AllCombs[:, 4],
          'lnAs': AllCombs[:, 5],
          'w': AllCombs[:, 6],
}

In [6]:
print(np.shape(params['h']))

(1400,)


In [7]:
np.size(AllCombs)                                                                   # 'n_samples' pts for 'n_params' parameters

9800

In [8]:
type(params)

dict

In [9]:
np.savez('LHS_params_7dim.npz', **params)                  # Save several arrays into a single file in uncompressed .npz format.

In [10]:
print(params['h'])
print(params['omega_b'])
print(params['omega_cdm'])
print(params['ns'])
print(params['z'])
print(params['lnAs'])
print(params['w'])
print(np.shape(params['h']))

[0.73436741 0.7487777  0.72761973 ... 0.77714081 0.63692638 0.63109364]
[0.02260329 0.01803503 0.02054682 ... 0.02133738 0.02046176 0.02255826]
[0.14292352 0.08502502 0.22955683 ... 0.16679771 0.07444603 0.22169407]
[0.88926376 0.97418156 0.8940243  ... 1.05099357 0.95552538 0.92966405]
[3.75696926 4.6147248  5.51822731 ... 3.31093638 0.11436741 5.79842745]
[3.8340243  2.79328091 3.9        ... 3.60729092 2.69664046 3.51436741]
[-1.48263045 -1.02330236 -0.6424589  ... -0.83738385 -1.26261615
 -0.68298785]
(1400,)


In [11]:
print(AllParams)
print(np.shape(AllParams))
AllParams_tran = np.transpose(AllParams)
print(np.shape(AllParams_tran))

[[ 6.20000000e-01  6.20114367e-01  6.20228735e-01 ...  7.79771265e-01
   7.79885633e-01  7.80000000e-01]
 [ 1.80000000e-02  1.80050036e-02  1.80100071e-02 ...  2.49899929e-02
   2.49949964e-02  2.50000000e-02]
 [ 5.00000000e-02  5.01429593e-02  5.02859185e-02 ...  2.49714081e-01
   2.49857041e-01  2.50000000e-01]
 ...
 [ 0.00000000e+00  5.71837026e-03  1.14367405e-02 ...  7.98856326e+00
   7.99428163e+00  8.00000000e+00]
 [ 2.60000000e+00  2.60092924e+00  2.60185847e+00 ...  3.89814153e+00
   3.89907076e+00  3.90000000e+00]
 [-1.50000000e+00 -1.49935668e+00 -1.49871337e+00 ... -6.01286633e-01
  -6.00643317e-01 -6.00000000e-01]]
(7, 1400)
(1400, 7)


In [1]:
# figure = corner.corner(AllParams_tran, labels=[r"$h$", r"$\Omega_{\mathrm{b}}$", r"$\Omega_{\mathrm{c}}$", r"$n_{s}$", r"$z$", r"$\ln{(10^{10}A_{s})}$", r"$w$" ],
#                        quantiles=[0.16, 0.5, 0.84],
#                        show_titles=True, title_kwargs={"fontsize": 12})